package com.example.national_id_project.Model;

import java.util.Date;

public class AutoGeneratedRespObj {

    public String transactionID;
    public String version;
    public String id;
    public Object errors;
    public Date responseTime;
    public Response response;

    public class Response{
        public boolean kycStatus;
        public String authToken;
        public Object thumbprint;
        public String identity;


        public boolean isKycStatus() {
            return kycStatus;
        }

        public void setKycStatus(boolean kycStatus) {
            this.kycStatus = kycStatus;
        }

        public String getAuthToken() {
            return authToken;
        }

        public void setAuthToken(String authToken) {
            this.authToken = authToken;
        }

        public Object getThumbprint() {
            return thumbprint;
        }

        public void setThumbprint(Object thumbprint) {
            this.thumbprint = thumbprint;
        }

        public String getIdentity() {
            return identity;
        }

        public void setIdentity(String identity) {
            this.identity = identity;
        }


        @Override
        public String toString() {
            return "Response{" +
                    "kycStatus=" + kycStatus +
                    ", authToken='" + authToken + '\'' +
                    ", thumbprint=" + thumbprint +
                    ", identity='" + identity + '\'' +
                    '}';
        }
    }


    public String getTransactionID() {
        return transactionID;
    }

    public void setTransactionID(String transactionID) {
        this.transactionID = transactionID;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Object getErrors() {
        return errors;
    }

    public void setErrors(Object errors) {
        this.errors = errors;
    }

    public Date getResponseTime() {
        return responseTime;
    }

    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    public Response getResponse() {
        return response;
    }

    public void setResponse(Response response) {
        this.response = response;
    }

    @Override
    public String toString() {
        return "AutoGeneratedRespObj{" +
                "transactionID='" + transactionID + '\'' +
                ", version='" + version + '\'' +
                ", id='" + id + '\'' +
                ", errors=" + errors +
                ", responseTime=" + responseTime +
                ", response=" + response +
                '}';
    }




}
